default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['POSTGRESQL_DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: myapp_development

production:
  <<: *default
  database: myapp_production
test:
  <<: *default
  database: myapp_test
